# 注册中心配置
registry:
  plugin-name: zookeeper
  servers: 127.0.0.1:2181
  namespace: dolphinscheduler
  base-sleep-time-ms: 60
  max-sleep-ms: 300
  max-retries: 5
  session-timeout-ms: 30000
  connection-timeout-ms: 7500
  block-until-cconnected-wwait: 600
  digest: 