# 创建service为alinesno-infra-data-${PROJECT_MASTER_NAME}
apiVersion: v1
kind: Service
metadata:
  name: alinesno-infra-data-${PROJECT_MASTER_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    app: alinesno-infra-data-${PROJECT_MASTER_NAME}
    release: canary
  ports:
    - name: http
      targetPort: 8080
      port: 8080

---
# 创建后端服务的pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alinesno-infra-data-${PROJECT_MASTER_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alinesno-infra-data-${PROJECT_MASTER_NAME}
      release: canary
  template:
    metadata:
      labels:
        app: alinesno-infra-data-${PROJECT_MASTER_NAME}
        release: canary
    spec:
      imagePullSecrets:
        - name: aliyun-docker-registry
      containers:
        - name: alinesno-infra-data-${PROJECT_MASTER_NAME}
          image: ${ALIYUN_CR_REGISTORY}/${ALIYUN_CR_NAMESPACE}/${PROJECT_MASTER_NAME}:${VERSION}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: |
                -Dspring.data.redis.host=${REDIS_HOST}
                -Dspring.data.redis.password=${REDIS_KEY}
                -Dregistry.servers=${ZOOKEEPER_HOST}
                -Dspring.datasource.url=jdbc:mysql://${DB_MYSQL_URL}/dev_alinesno_infra_dolphinscheduler_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
                -Dspring.datasource.username=${DB_MYSQL_USRENAME}
                -Dspring.datasource.password=${DB_MYSQL_PASSWORD}
                -Dserver.port=8080
          ports:
            - name: http
              containerPort: 8080