CREATE TABLE IF NOT EXISTS scheduled_tasks (
    task_name VARCHAR(100) COMMENT '任务名称',
    task_instance VARCHAR(100) COMMENT '任务实例',
    task_data LONGBLOB COMMENT '任务数据',
    execution_time TIMESTAMP COMMENT '执行时间',
    picked BIT COMMENT '是否已被提取',
    picked_by VARCHAR(50) COMMENT '提取者',
    last_success TIMESTAMP COMMENT '最后成功时间',
    last_failure TIMESTAMP COMMENT '最后失败时间',
    consecutive_failures INT COMMENT '连续失败次数',
    last_heartbeat TIMESTAMP COMMENT '最后心跳时间',
    version BIGINT COMMENT '版本',
    PRIMARY KEY (task_name, task_instance)
) COMMENT='定时任务表';


CREATE TABLE IF NOT EXISTS job_queue (
    `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
    `delete_manager` BIGINT COMMENT '删除的人',
    `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
    `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
    `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
    `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
    `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
    `id` BIGINT COMMENT '唯一ID号',
    `field_prop` VARCHAR(255) COMMENT '字段属性',
    `add_time` DATETIME COMMENT '添加时间',
    `delete_time` DATETIME COMMENT '删除时间',
    `has_status` INT COMMENT '状态(0启用|1禁用)',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
    `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
    `job_name` VARCHAR(255) NOT NULL COMMENT '转移名称',
    `job_id` BIGINT COMMENT '任务ID',
    `job_data` VARCHAR(255) COMMENT '转移数据',
    `status` VARCHAR(255) COMMENT '状态',
    `step` INT COMMENT '当前执行到的步骤',
    PRIMARY KEY (`id`)
)COMMENT='任务队列表';

CREATE TABLE IF NOT EXISTS job (
    `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
    `delete_manager` BIGINT COMMENT '删除的人',
    `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
    `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
    `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
    `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
    `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
    `id` BIGINT COMMENT '唯一ID号',
    `field_prop` VARCHAR(255) COMMENT '字段属性',
    `add_time` DATETIME COMMENT '添加时间',
    `delete_time` DATETIME COMMENT '删除时间',
    `has_status` INT COMMENT '状态(0启用|1禁用)',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
    `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
    `trans_ids` VARCHAR(255) COMMENT '关联的转换任务id',
    `git_id` VARCHAR(255) COMMENT '仓库名称',
    `relative_location` VARCHAR(255) COMMENT '作业文件路径',
    `job_context` LONGTEXT COMMENT '任务的上下文',
    `name` VARCHAR(255) COMMENT '名称',
    `description` VARCHAR(255) COMMENT '描述',
    `type` VARCHAR(255) COMMENT '类型',
    `path` VARCHAR(255) COMMENT '路径',
    `quartz` VARCHAR(255) COMMENT 'Quartz',
    `strategy` VARCHAR(255) COMMENT '同步策略',
    `log_level` VARCHAR(255) COMMENT '日志级别',
    `status` VARCHAR(10)  COMMENT '状态',
    `category_id` VARCHAR(255) COMMENT '分类ID'
) COMMENT='任务表';


CREATE TABLE IF NOT EXISTS trans (
    `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
    `delete_manager` BIGINT COMMENT '删除的人',
    `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
    `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
    `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
    `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
    `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
    `id` BIGINT COMMENT '唯一ID号',
    `field_prop` VARCHAR(255) COMMENT '字段属性',
    `add_time` DATETIME COMMENT '添加时间',
    `delete_time` DATETIME COMMENT '删除时间',
    `has_status` INT COMMENT '状态(0启用|1禁用)',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
    `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
    `git_id` VARCHAR(255) COMMENT '仓库名称',
    `relative_location` VARCHAR(255) COMMENT '转换文件路径',
    `trans_context` LONGTEXT COMMENT '任务的上下文',
    `job_id` BIGINT COMMENT '关联的任务id',
    `order_step` INT COMMENT '任务排序',
    `process_data_count` INT COMMENT '处理完成的数据',
    `total_data_count` INT COMMENT '需要处理的数据量',
    `context_script` VARCHAR(255) COMMENT '脚本信息',
    `parent_step` VARCHAR(255) COMMENT '父类步骤',
    `plugin_name` VARCHAR(255) COMMENT '插件名称',
    `name` VARCHAR(255) COMMENT '名称',
    `description` VARCHAR(255) COMMENT '描述',
    `type` VARCHAR(255) COMMENT '类型',
    `path` VARCHAR(255) COMMENT '路径',
    `quartz` VARCHAR(255) COMMENT 'Quartz',
    `strategy` VARCHAR(255) COMMENT '同步策略',
    `log_level` VARCHAR(255) COMMENT '日志级别',
    `status` VARCHAR(10) COMMENT '状态',
    `category_id` VARCHAR(255) COMMENT '分类ID'
) COMMENT='数据转换表';


CREATE TABLE IF NOT EXISTS `base_kettle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(255) DEFAULT NULL COMMENT '名称',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `type` varchar(255) DEFAULT NULL COMMENT '类型',
  `path` varchar(255) DEFAULT NULL COMMENT '路径',
  `quartz` varchar(255) DEFAULT NULL COMMENT 'Quartz',
  `sync_strategy` varchar(255) DEFAULT NULL COMMENT '同步策略',
  `log_level` varchar(255) DEFAULT NULL COMMENT '日志级别',
  `status` varchar(255) DEFAULT NULL COMMENT '状态',
  `category_id` varchar(255) DEFAULT NULL COMMENT '分类ID',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` varchar(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` datetime COMMENT '添加时间',
  `delete_time` datetime COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='base_kettle';


CREATE TABLE IF NOT EXISTS `build_git` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `git_name` varchar(255) DEFAULT NULL COMMENT '仓库名称',
  `git_icon` varchar(255) DEFAULT NULL COMMENT '仓库图标',
  `git_host` varchar(255) DEFAULT NULL COMMENT '仓库地址',
  `git_url` varchar(255) DEFAULT NULL COMMENT '仓库地址',
  `branch_name` varchar(255) DEFAULT NULL COMMENT '项目分支',
  `git_user_name` varchar(255) DEFAULT NULL COMMENT 'gitlab账号',
  `password` varchar(255) DEFAULT NULL COMMENT 'gitlab账号密码',
  `git_user_id` int(11) DEFAULT NULL COMMENT 'gitlab账号id',
  `git_namespace` varchar(255) DEFAULT NULL COMMENT '仓库空间',
  `git_type` varchar(255) DEFAULT NULL COMMENT '仓库类型',
  `inner_git` int(11) DEFAULT NULL COMMENT '内置gitlab',
  `has_bing` int(11) DEFAULT NULL COMMENT '是否绑定',
  `refresh_token` varchar(255) DEFAULT NULL COMMENT '刷新token',
  `expires_in` int(11) DEFAULT NULL COMMENT '超时时间',
  `bing_git_info` varchar(255) DEFAULT NULL COMMENT '绑定第三方git账号信息',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` varchar(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` datetime COMMENT '添加时间',
  `delete_time` datetime COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='build_git';


CREATE TABLE IF NOT EXISTS `category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_name` VARCHAR(255) DEFAULT NULL COMMENT 'categoryName',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='category';


CREATE TABLE IF NOT EXISTS `job_monitor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `monitor_job_id` VARCHAR(255) DEFAULT NULL COMMENT '监控任务ID',
  `monitor_success` INT COMMENT '监控成功次数',
  `monitor_fail` INT COMMENT '监控失败次数',
  `monitor_status` INT COMMENT '监控状态',
  `run_status` VARCHAR(255) DEFAULT NULL COMMENT '运行状态',
  `last_execute_time` DATETIME COMMENT '上次执行时间',
  `next_execute_time` DATETIME COMMENT '下次执行时间',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='job_monitor';


CREATE TABLE IF NOT EXISTS `job_run_his` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `run_job_id` VARCHAR(255) DEFAULT NULL COMMENT '作业ID',
  `start_time` DATETIME COMMENT '执行开始时间',
  `end_time` DATETIME COMMENT '执行结束时间',
  `run_status` INT COMMENT '作业执行结果,0:失败；1:成功',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '作业执行日志',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='job_run_his';


CREATE TABLE IF NOT EXISTS `quartz` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `quartz_description` VARCHAR(255) DEFAULT NULL COMMENT '任务描述',
  `quartz_cron` VARCHAR(255) DEFAULT NULL COMMENT '定时策略',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='quartz';


CREATE TABLE IF NOT EXISTS `trans_monitor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `monitor_transid` VARCHAR(255) DEFAULT NULL COMMENT '监控转换ID',
  `monitor_success` INT COMMENT '监控成功次数',
  `monitor_fail` INT COMMENT '监控失败次数',
  `monitor_status` INT COMMENT '监控状态',
  `run_status` VARCHAR(255) DEFAULT NULL COMMENT '运行状态',
  `last_execute_time` DATETIME COMMENT '上次执行时间',
  `next_execute_time` DATETIME COMMENT '下次执行时间',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trans_monitor';


CREATE TABLE IF NOT EXISTS `trans_run_his` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `monitor_trans_id` VARCHAR(255) DEFAULT NULL COMMENT '转换ID',
  `start_time` DATETIME COMMENT '执行开始时间',
  `end_time` DATETIME COMMENT '执行结束时间',
  `run_status` INT COMMENT '转换执行结果,0:失败；1:成功',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '转换执行日志',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trans_run_his';
