server:
  port: 30400

spring:
  application:
    name: demo-config-simples
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local

alinesno.ops:
  scheduler:
    env: development
    kafkaServers: 192.168.101.18:9092
    user-key: aip@local